package xyz.cliserkad.consortium;

/**
 * Represents an action that a player can take,
 * generated by a PlayerController
 */
public sealed interface PlayerAction permits
	PurchaseAction,
	EndTurnAction
{ }
