name: Build and Release

# Build every time we push to main or master, or manually trigger the workflow
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          # this distribution is cached by github actions
          distribution: 'temurin'
          # jdk version to use, specified in pom.xml
          java-version: '21'
          # use the github actions cached jdk if available.
          check-latest: false
      - name: Generate Maven settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github-smp", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.TOKEN }}"}]'
      - name: Package client jar
        id: package
        run: mvn -B clean package --file pom.xml --no-transfer-progress
      - name: Publish client artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.package.outcome == 'success' }}
        with:
          SOURCE_FILE: 'target/consortium.jar'
          DEST_NAME: 'consortium.jar'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-release
          name: auto-release-${{ github.sha }}
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            target/consortium.jar
            src/scripts/consortium-windows.bat
            src/scripts/consortium-macos.zsh
      - name: Move auto-release tag to current commit
        uses: EndBug/latest-tag@latest
        with:
          ref: auto-release
